#  1
#  4 4
#  9 9 9
#  16 16 16 16
#  25 25 25 25 25



# n=int(input("enter the number"))
# i=1
# while i<=n:
#     j=1
#     while j<=i:
#         print(i*i,end=" ")
#         j=j+1
#     i=i+1
#     print()
        
# a=int(input("enter the number"))
# i=1
# while i<=a:
#     j=1
#     while j<=i:
#         if i%2==0:
#             print(i*i,end=" ")
#         else:
#             print(i*i,end=" ")
#         j=j+1
#     i=i+1
#     print()